feed/feed/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('feedapp.urls')),
    path('', include('social_django.urls'))
]

feed/feedapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('reports/', views.reports, name='reports'),
]

feed/feedapp/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    date_posted = models.DateTimeField(auto_now_add=True)
    hidden = models.BooleanField(default=False)
    date_hidden = models.DateTimeField(blank=True, null=True)
    hidden_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                  blank=True, null=True, related_name='mod_who_hid')

    def __str__(self):
        return self.text


class Report(models.Model):
    reported_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

feed/feedapp/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'feedapp/index.html')


def reports(request):
    return render(request, 'feedapp/reports.html')

feed/feedapp/templates/feedapp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css"
    />
  </head>
  <body>
    <section class="hero is-info">
      <div class="hero-head">
        <nav class="navbar" role="navigation" aria-label="main navigation">
          <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start pl-2">
              <a href="/" class="navbar-item">Home</a>
              {% if perms.feedapp.view_report %}
              <a href="{% url 'reports' %}" class="navbar-item">Reports</a>
              {% endif %}
            </div>
            <div class="navbar-end pr-2">
              <div class="navbar-item">
                <div class="buttons">
                  {% if user.is_authenticated %}
                  <a class="button is-primary" href="/logout/">Logout</a>
                  {% else %}
                  <a class="button is-primary" href="/login/auth0">Login</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </nav>
        <div class="hero-body">
          <div class="container has-text-centered">
            <p class="title">{% block main_title %}{% endblock %}</p>
            <p class="subtitle">{% block sub_title %}{% endblock %}</p>
          </div>
        </div>
      </div>
    </section>
    <section class="section">
      <div class="container">{% block content %}{% endblock %}</div>
    </section>
  </body>
</html>

feed/feedapp/templates/feedapp/index.html
{% extends 'feedapp/base.html' %} 
{% block title %}Home{% endblock %} 
{% block main_title %}Public Feed{% endblock %} 
{% block sub_title %} Leave a message for everyone to see!{% endblock %} 
{% block content %}
{% endblock %}

feed/feedapp/templates/feedapp/reports.html
{% extends 'feedapp/base.html' %} 
{% block title %}Reported Posts{% endblock %}
{% block main_title %}Reported Posts{% endblock %} 
{% block content %}
{%endblock %}